/**
 * Ambient types for the generated wasm-bindgen glue `web/assets/lineformat.js`
 * (machine-generated by `make wasm-lineformat`, no JSDoc). The dynamic import
 * in `web/src/lineformat.mjs` resolves through this module declaration, so
 * call sites get real types without tsc checking the generated source.
 */

/**
 * Parse one rollout wire line `<ts>\0<json>` into
 * `{ ts, type, text, truncated }`. Throws when the ts prefix is invalid.
 *
 * @param {string} line one physical rollout line (without trailing newline)
 * @param {number} max byte limit for the payload text
 * @returns {{ ts: number, type: string, text: string, truncated: boolean }}
 */
export function parse_line(line: string, max: number): {
  ts: number;
  type: string;
  text: string;
  truncated: boolean;
};

/**
 * Cheap validity check: does the line start with `<ascii digits>\0`?
 *
 * @param {string} line
 * @returns {boolean}
 */
export function is_valid(line: string): boolean;

/**
 * Lenient metadata extraction from a (possibly truncated) `tool_call` event
 * JSON payload — no JSON parse, a literal scan shared with the server.
 * `*_pretty_head` carry the raw (possibly cut) payload string contents.
 *
 * @param {string} text the (possibly truncated) tool_call JSON payload
 * @returns {{
 *   tool: string;
 *   duration_ms: number;
 *   bytes_up: number;
 *   bytes_down: number;
 *   ts: number;
 *   args_pretty_head: string;
 *   result_pretty_head: string;
 * } | null} null when the metadata fields are missing
 */
export function extract_tool_call_meta(text: string): {
  tool: string;
  duration_ms: number;
  bytes_up: number;
  bytes_down: number;
  ts: number;
  args_pretty_head: string;
  result_pretty_head: string;
} | null;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
  readonly memory: WebAssembly.Memory;
  readonly is_valid: (a: number, b: number) => number;
  readonly parse_line: (a: number, b: number, c: number) => [number, number, number];
  readonly __wbindgen_exn_store: (a: number) => void;
  readonly __externref_table_alloc: () => number;
  readonly __wbindgen_externrefs: WebAssembly.Table;
  readonly __wbindgen_malloc: (a: number, b: number) => number;
  readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
  readonly __externref_table_dealloc: (a: number) => number;
  readonly __wbindgen_free: (a: number, b: number, c: number) => void;
  readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiate the wasm module, fetching `lineformat_bg.wasm` relative to the
 * glue's own module URL (requires serving over HTTP, not file://).
 *
 * @param {{ module: SyncInitInput } | SyncInitInput} [module_or_path]
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init(
  module_or_path?: { module: SyncInitInput } | SyncInitInput,
): Promise<InitOutput>;
