/**
 * Ambient types for the generated wasm-bindgen glue `web/assets/pretty-json.js`
 * (machine-generated by `make wasm-pretty`, no JSDoc). The dynamic import in
 * `web/src/pretty.mjs` resolves through this module declaration, so call sites
 * get real types without tsc checking the generated source.
 */

/**
 * Pretty-print `input`, which may be well-formed JSON or JSON truncated
 * mid-token (optionally ending in a single `…`).
 *
 * For well-formed input with indent 2 the output is byte-identical to
 * `serde_json::to_string_pretty`. Never panics; garbage is echoed leniently.
 *
 * @param {string} input the (possibly abridged) JSON text
 * @param {number} indent indent width, typically 2 or 4
 * @returns {string} pretty-printed text with open brackets closed
 */
export function pretty_print(input: string, indent: number): string;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
  readonly memory: WebAssembly.Memory;
  readonly pretty_print: (a: number, b: number, c: number) => [number, number];
  readonly __wbindgen_externrefs: WebAssembly.Table;
  readonly __wbindgen_malloc: (a: number, b: number) => number;
  readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
  readonly __wbindgen_free: (a: number, b: number, c: number) => void;
  readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiate the wasm module, fetching `pretty-json_bg.wasm` relative to the
 * glue's own module URL (requires serving over HTTP, not file://).
 *
 * @param {{ module: SyncInitInput } | SyncInitInput} [module_or_path]
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init(
  module_or_path?: { module: SyncInitInput } | SyncInitInput,
): Promise<InitOutput>;
