/**
 * Ambient types for the generated wasm-bindgen glue `web/assets/validators.js`
 * (machine-generated by `make wasm-validators`, no JSDoc). The dynamic import
 * in `web/src/wasm-validators.mjs` resolves through this module declaration,
 * so call sites get real types without tsc checking the generated source.
 *
 * One `validate_*` export per schema stem. Each takes a parsed JSON value
 * and returns a JS array of `{ instancePath, schemaPath }` error objects —
 * the identical contract as the generated `.mjs` validators; an empty array
 * means valid.
 */

export type ValidateResult = { instancePath: string; schemaPath: string };

export function validate_ack(instance: unknown): ValidateResult[];
export function validate_assistant(instance: unknown): ValidateResult[];
export function validate_console_entry(instance: unknown): ValidateResult[];
export function validate_error(instance: unknown): ValidateResult[];
export function validate_pong(instance: unknown): ValidateResult[];
export function validate_ready(instance: unknown): ValidateResult[];
export function validate_rename(instance: unknown): ValidateResult[];
export function validate_session_meta(instance: unknown): ValidateResult[];
export function validate_session_rename(instance: unknown): ValidateResult[];
export function validate_tool_call(instance: unknown): ValidateResult[];

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
  readonly memory: WebAssembly.Memory;
  readonly validate_ack: (a: number) => number;
  readonly validate_assistant: (a: number) => number;
  readonly validate_console_entry: (a: number) => number;
  readonly validate_error: (a: number) => number;
  readonly validate_pong: (a: number) => number;
  readonly validate_ready: (a: number) => number;
  readonly validate_rename: (a: number) => number;
  readonly validate_session_meta: (a: number) => number;
  readonly validate_session_rename: (a: number) => number;
  readonly validate_tool_call: (a: number) => number;
  readonly __wbindgen_exn_store: (a: number) => void;
  readonly __externref_table_alloc: () => number;
  readonly __wbindgen_externrefs: WebAssembly.Table;
  readonly __wbindgen_malloc: (a: number, b: number) => number;
  readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
  readonly __externref_table_dealloc: (a: number) => void;
  readonly __wbindgen_free: (a: number, b: number, c: number) => void;
  readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiate the wasm module, fetching `validators_bg.wasm` relative to the
 * glue's own module URL (requires serving over HTTP, not file://).
 *
 * @param {{ module: SyncInitInput } | SyncInitInput} [module_or_path]
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init(
  module_or_path?: { module: SyncInitInput } | SyncInitInput,
): Promise<InitOutput>;
